<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
 <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Start Page</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body>
        <h1>Sign in here</h1>
        <form action="/inputChooser" method="POST">
            <label for="username">First name:</label>
            <input type="text" id="username" name="username"></input>
            <label for="password">Last name:</label>
            <input type="text" id="password" name="password"></input>
            <input type="submit" name="logIn" value="Log In"></input>
        </form>
    </body>
</html>